# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/trq_minisys_rv-new/ip/ip_divider/ip_divider.xci
# IP: The module: 'ip_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/trq_minisys_rv-new/ip/ip_divider/ip_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_divider'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/trq_minisys_rv-new/ip/ip_divider/ip_divider.xci
# IP: The module: 'ip_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/trq_minisys_rv-new/ip/ip_divider/ip_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
